services:
  machine_teaching_db:
    image: postgres:13.14
    env_file: ./machine-teaching-db/.env
    volumes:
      - ./machine-teaching-db/data/dump.sql:/docker-entrypoint-initdb.d/create_tables.sql
    ports:
      - 5432:5432
  web:
    build: .
    volumes:
      - ./machineteaching:/app/machineteaching
    ports:
      - 8020:8020
    env_file: ./.env
    depends_on:
      - machine_teaching_db
