services:
  machine_teaching_db:
    image: postgres:15.10
    env_file: ./machine-teaching-db/.env
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./machine-teaching-db/data/dump.sql:/docker-entrypoint-initdb.d/create_tables.sql
    ports:
      - 5432:5432
    restart: always
  web:
    build: .
    volumes:
      - ./machineteaching:/app/machineteaching
    ports:
      - 80:8020
    env_file: ./machineteaching/.env
    depends_on:
      - machine_teaching_db
    restart: on-failure
  worker_node:
    build:
      context: ./worker-node/worker_node
    ports:
      - 5000:5000
    depends_on:
      - web
      - machine_teaching_db
volumes:
  db-data:
    driver:
      local
