services:
  machine_teaching_db:
    image: postgres:13.14
    env_file: ./machine-teaching-db/.env
    volumes:
      - ./machine-teaching-db/data/dump.sql:/docker-entrypoint-initdb.d/create_tables.sql
    ports:
      - 5432:5432
  web:
    build: .
    volumes:
      - ./machineteaching:/app/machineteaching
    ports:
      - 8020:8020
    env_file: ./machineteaching/.env
    depends_on:
      - machine_teaching_db
  worker_node:
    build:
      context: ./worker-node/worker_node
    ports:
      - 5000:5000
    depends_on:
      - web
      - machine_teaching_db
