version: "3.7"
services:
  machine_teaching_db:
    image: postgres:9.6
    env_file: ./machine-teaching-db/.env
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    restart: always
  web:
    build: .
    volumes:
      - ./machineteaching:/app/machineteaching
    ports:
      - "80:8020"
    env_file: ./machineteaching/.env
    depends_on:
      - machine_teaching_db
    restart: on-failure
volumes:
  db-data:
    driver:
      local
