services:
  machine_teaching_db:
    image: postgres:15.10
    env_file: ./machine-teaching-db/.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./machine-teaching-db/data/dump.sql:/docker-entrypoint-initdb.d/create_tables.sql
    ports:
      - 5435:5432
  web:
    build: .
    working_dir: /app/machineteaching
    volumes:
      - ./machineteaching:/app/machineteaching
    ports:
      - 8020:8020
    env_file: ./machineteaching/.env
    depends_on:
      - machine_teaching_db
      - ollama
  worker_node:
    build:
      context: ./worker-node/worker_node
    ports:
      - 5000:5000
    depends_on:
      - web
      - machine_teaching_db
  ollama:
    image: ollama/ollama:latest
    ports:
      - 11434:11434
    volumes:
      - ollama_data:/root/.ollama

volumes:
  ollama_data:
  postgres_data:
