version: "3.7"
services:
  machine_teaching_db:
    image: postgres:9.6
    environment:
      - POSTGRES_USER=dev_user
      - POSTGRES_PASSWORD=secure_password
      - POSTGRES_DB=machine_teaching_db
    ports:
      - 5432:5432
  web:
    build: .
    volumes:
      - ./machineteaching:/app/machineteaching
    ports:
      - "8020:8020"
    environment:
      - DB_NAME=machine_teaching_db
      - DB_USER=dev_user
      - DB_PASSWORD=secure_password
      - DB_HOST=machine_teaching_db
      - DB_PORT=5432
      - ENVIRONMENT=DEV
      - PORT=8020
      - WAIT_HOSTS=machine_teaching_db:5432
    depends_on:
      - machine_teaching_db