# Generated by Django 2.0.1 on 2018-01-17 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('difficulty', models.CharField(max_length=200)),
                ('link', models.URLField()),
                ('retrieved_date', models.DateField()),
                ('crawler', models.CharField(max_length=200)),
                ('hint', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('link', models.URLField()),
                ('retrieved_date', models.DateField()),
                ('ignore', models.BooleanField(default=False)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='questions.Problem')),
            ],
        ),
    ]
