# Generated by Django 2.0.1 on 2018-01-17 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='retrieved_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='solution',
            name='retrieved_date',
            field=models.DateTimeField(),
        ),
    ]
