# Generated by Django 2.0.1 on 2018-08-24 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_auto_20180117_1454'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('content', models.TextField()),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='questions.Problem')),
            ],
        ),
        migrations.AlterField(
            model_name='solution',
            name='retrieved_date',
            field=models.DateTimeField(),
        ),
    ]
