# Generated by Django 2.0.1 on 2018-08-24 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0004_auto_20180824_1710'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testcase',
            name='name',
        ),
    ]
