# Generated by Django 2.0.1 on 2018-08-24 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0005_remove_testcase_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='solution',
            name='header',
            field=models.TextField(default='Not set yet'),
            preserve_default=False,
        ),
    ]
