# Generated by Django 2.0.1 on 2018-08-24 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0008_auto_20180824_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solution',
            name='tip',
            field=models.TextField(blank=True, default='#Start your python function here'),
        ),
    ]
