# Generated by Django 2.1 on 2018-08-26 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0009_auto_20180824_2112'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solution', models.TextField(blank=True)),
                ('outcome', models.CharField(choices=[('F', 'Failed'), ('P', 'Passed'), ('S', 'Skipped')], max_length=2)),
                ('seconds_in_code', models.IntegerField()),
                ('seconds_in_page', models.IntegerField()),
                ('seconds_to_begin', models.IntegerField()),
                ('solution_lines', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='questions.Problem')),
            ],
        ),
    ]
