# Generated by Django 2.0.1 on 2018-10-19 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0016_auto_20181017_1840'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='programming',
        ),
    ]
