# Generated by Django 2.1 on 2018-10-19 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0017_remove_userprofile_programming'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='programming',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=3),
            preserve_default=False,
        ),
    ]
