# Generated by Django 2.1 on 2018-10-19 21:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0018_userprofile_programming'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlog',
            name='problem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.Problem'),
        ),
        migrations.AlterField(
            model_name='userlog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
