# Generated by Django 2.1 on 2018-10-19 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0020_auto_20181019_2138'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='accepted',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
