# Generated by Django 2.1 on 2018-10-19 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0021_userprofile_accepted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='professor',
            field=models.CharField(blank=True, choices=[('carla', 'Carla'), ('joao', 'João Carlos')], max_length=5),
        ),
    ]
