# Generated by Django 2.1 on 2018-10-19 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0022_auto_20181019_2211'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='strategy',
            field=models.CharField(choices=[('ordered', 'ordered'), ('eer', 'eer')], default='eer', max_length=10),
            preserve_default=False,
        ),
    ]
