# Generated by Django 2.1 on 2018-11-01 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0025_userprofile_seed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='professor',
            field=models.CharField(blank=True, choices=[('carla', 'Carla'), ('joao', 'João Carlos'), ('hugo', 'Hugo'), ('fernanda', 'Fernanda'), ('kleber', 'Kleber'), ('cadu', 'Cadu')], max_length=5),
        ),
    ]
