# Generated by Django 2.1.1 on 2018-11-13 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0029_auto_20181107_2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='professor',
            field=models.CharField(blank=True, choices=[('carla', 'Carla'), ('joao', 'João Carlos'), ('hugo', 'Hugo'), ('fernanda', 'Fernanda'), ('kleber', 'Kleber'), ('cadu', 'Cadu'), ('alan', 'Alan')], max_length=30),
        ),
    ]
