# Generated by Django 2.1.7 on 2019-05-03 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0029_auto_20181107_2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlog',
            name='error_type',
            field=models.CharField(choices=[('C', 'Conceptual'), ('S', 'Syntax'), ('D', 'Distraction'), ('I', 'Interpretation')], default='D', max_length=2),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='professor',
            field=models.CharField(blank=True, choices=[('carla', 'Carla'), ('joao', 'João Carlos'), ('hugo', 'Hugo'), ('fernanda', 'Fernanda'), ('kleber', 'Kleber'), ('cadu', 'Cadu'), ('alan', 'Alan')], max_length=30),
        ),
    ]
