# Generated by Django 2.1.1 on 2019-05-08 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0031_auto_20190508_0233'),
        ('questions', '0030_auto_20181113_2239'),
    ]

    operations = [
    ]
