# Generated by Django 2.2.1 on 2019-08-08 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0033_auto_20190808_1222'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='professor2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='questions.Professor'),
        ),
        migrations.AlterField(
            model_name='professor',
            name='prof_class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='questions.OnlineClass'),
        ),
    ]
