# Generated by Django 2.2.1 on 2019-08-08 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0035_add_professor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='professor',
        ),
    ]
