# Generated by Django 2.2.1 on 2019-08-08 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0036_remove_userprofile_professor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='professor2',
            new_name='professor',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='strategy',
            field=models.CharField(choices=[('random', 'random'), ('eer', 'eer'), ('sequential', 'sequential')], max_length=10),
        ),
    ]
