# Generated by Django 2.2.1 on 2019-08-08 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0038_merge_professors'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterModelOptions(
            name='onlineclass',
            options={'verbose_name_plural': 'OnlineClasses'},
        ),
        migrations.AddField(
            model_name='problem',
            name='chapter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='questions.Chapter'),
        ),
    ]
