# Generated by Django 2.2.1 on 2019-08-19 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0042_auto_20190808_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='link',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='problem',
            name='retrieved_date',
            field=models.DateTimeField(blank=True),
        ),
    ]
