# Generated by Django 2.2.1 on 2019-08-19 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0043_auto_20190819_1701'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='test_case_generator',
            field=models.TextField(blank=True, null=True),
        ),
    ]
