# Generated by Django 2.2.1 on 2019-08-19 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0044_problem_test_case_generator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='chapter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='questions.Chapter'),
        ),
    ]
