# Generated by Django 2.1.7 on 2019-08-28 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0046_create_userlogview'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLogView',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outcome', models.CharField(max_length=2)),
                ('timestamp', models.DateTimeField()),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.AddField(
            model_name='professor',
            name='assistant',
            field=models.BooleanField(default=False),
        ),
    ]
