# Generated by Django 2.2.5 on 2020-07-28 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0049_auto_20200728_1823'),
    ]

    operations = [
        migrations.AddField(
            model_name='onlineclass',
            name='class_code',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
