# Generated by Django 2.2.5 on 2020-07-28 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0050_onlineclass_class_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='onlineclass',
            name='class_code',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
    ]
