# Generated by Django 2.2.5 on 2020-07-28 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0051_auto_20200728_1933'),
    ]

    operations = [
        migrations.RenameField(
            model_name='onlineclass',
            old_name='chapters',
            new_name='chapter',
        ),
    ]
