# Generated by Django 2.2.5 on 2020-07-28 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0053_auto_20200728_2011'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlog',
            name='console',
            field=models.TextField(blank=True),
        ),
    ]
