# Generated by Django 3.0.8 on 2020-08-05 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0056_auto_20200805_0225'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproblem',
            name='options',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='problem',
            name='options',
            field=models.TextField(blank=True),
        ),
    ]
