# Generated by Django 2.2.5 on 2020-09-07 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0058_userprofile_read'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalproblem',
            name='chapter',
        ),
        migrations.AlterField(
            model_name='historicalsolution',
            name='header',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='problem',
            name='chapter',
        ),
        migrations.AddField(
            model_name='problem',
            name='chapter',
            field=models.ManyToManyField(to='questions.Chapter'),
        ),
        migrations.AlterField(
            model_name='solution',
            name='header',
            field=models.TextField(blank=True, null=True),
        ),
    ]
