# Generated by Django 2.2.5 on 2020-11-16 21:53

from django.conf import settings
from django.db import migrations, models
from django.utils import timezone
import django.db.models.deletion
import simple_history.models

def copy_onlineclass_chapter(apps, schema_editor):
    OnlineClass = apps.get_model('questions', "OnlineClass")
    Deadline = apps.get_model('questions', "Deadline")

    for obj_onlineclass in OnlineClass.objects.all():
        for chapter in obj_onlineclass.chapter.all():
            deadline = Deadline()
            deadline.deadline = timezone.now()
            deadline.onlineclass = obj_onlineclass
            deadline.chapter = chapter
            deadline.save()

def uncopy_onlineclass_chapter(apps, schema_editor):
    Deadline = apps.get_model('questions', "Deadline")
    Deadline.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('questions', '0061_create_userlogview'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalDeadline',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('deadline', models.DateTimeField()),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('chapter', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='questions.Chapter')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('onlineclass', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='questions.OnlineClass')),
            ],
            options={
                'verbose_name': 'historical Deadline',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Deadline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deadline', models.DateTimeField()),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.Chapter')),
                ('onlineclass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.OnlineClass')),
            ],
            options={
                'verbose_name': 'Deadline',
                'verbose_name_plural': 'Deadlines',
            },
        ),
        migrations.RunPython(copy_onlineclass_chapter, uncopy_onlineclass_chapter),
        migrations.RemoveField(
            model_name='onlineclass',
            name='chapter',
        ),
        migrations.AlterField(
            model_name='historicalproblem',
            name='retrieved_date',
            field=models.DateTimeField(blank=True, editable=False),
        ),
        migrations.AlterField(
            model_name='historicalsolution',
            name='retrieved_date',
            field=models.DateTimeField(blank=True, editable=False),
        ),
        migrations.AlterField(
            model_name='problem',
            name='retrieved_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='solution',
            name='cluster',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='questions.Cluster'),
        ),
        migrations.AlterField(
            model_name='solution',
            name='retrieved_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
