# Generated by Django 2.2.5 on 2020-11-17 16:14

from django.db import migrations, models
import django.db.models.deletion

def create_through_relations(apps, schema_editor):
    Problem = apps.get_model('questions', 'Problem')
    ExerciseSet = apps.get_model('questions', 'ExerciseSet')
    for problem in Problem.objects.all():
        for chapter in problem.chapter.all():
            ExerciseSet(
                problem=problem,
                chapter=chapter,
                order=1).save()

class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0062_auto_20201116_1853'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExerciseSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.Chapter')),
            ],
            options={
                'verbose_name': 'Exercise Set',
                'verbose_name_plural': 'Exercises Sets',
            },
        ),
        migrations.AddField(
            model_name='exerciseset',
            name='problem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.Problem'),
        ),
        migrations.RunPython(create_through_relations, reverse_code=migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='problem',
            name='chapter',
        ),
        migrations.AddField(
            model_name='problem',
            name='chapter',
            field=models.ManyToManyField(through='questions.ExerciseSet', to='questions.Chapter'),
        ),
    ]
