# Generated by Django 2.2.5 on 2020-11-17 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0063_auto_20201117_1314'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaldeadline',
            name='onlineclass',
        ),
        migrations.RemoveField(
            model_name='deadline',
            name='onlineclass',
        ),
        migrations.AddField(
            model_name='deadline',
            name='onlineclass',
            field=models.ManyToManyField(to='questions.OnlineClass'),
        ),
    ]
