# Generated by Django 2.2.5 on 2020-11-17 23:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0065_auto_20201117_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deadline',
            name='onlineclass',
            field=models.ManyToManyField(limit_choices_to={'active': True}, to='questions.OnlineClass'),
        ),
        migrations.CreateModel(
            name='UserLogError',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('error', models.CharField(max_length=255)),
                ('userlog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.UserLog')),
            ],
        ),
    ]
