# Generated by Django 3.1.2 on 2020-11-18 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0066_auto_20201117_2025'),
    ]

    operations = [
        migrations.AddField(
            model_name='onlineclass',
            name='chapter',
            field=models.ManyToManyField(to='questions.Chapter'),
        ),
    ]
