# Generated by Django 2.2.5 on 2020-12-05 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0067_onlineclass_chapter'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlog',
            name='test_case_hits',
            field=models.IntegerField(blank=True, null=True),
        ),
        #migrations.RunSQL("ALTER TABLE questions_userlog ADD COLUMN test_case_hits INTEGER")
    ]
