# Generated by Django 2.2.5 on 2021-02-10 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0071_auto_20201216_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcase',
            name='problem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.Problem'),
        ),
    ]
