# Generated by Django 2.2.5 on 2021-02-10 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0072_auto_20210210_1053'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaluserprofile',
            name='course',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='userlog',
            name='test_case_hits',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='course',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
