# Generated by Django 2.2.5 on 2021-02-10 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0072_auto_20210210_1053'),
    ]

    operations = [
    ]
