# Generated by Django 3.0.8 on 2021-03-07 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0074_recommendations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='onlineclass',
            name='chapter',
        ),
    ]
