# Generated by Django 3.2.9 on 2021-11-22 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0076_auto_20210416_0225'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'Comment'},
        ),
        migrations.AddField(
            model_name='historicalsolution',
            name='advanced_libraries',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='solution',
            name='advanced_libraries',
            field=models.BooleanField(default=False),
        ),
    ]
