# Generated by Django 3.0.8 on 2021-09-14 02:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0078_dropoutmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='drop_out_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='questions.DropOutModel'),
        ),
        migrations.AddField(
            model_name='historicalchapter',
            name='drop_out_model',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='questions.DropOutModel'),
        ),
        migrations.AlterField(
            model_name='dropoutmodel',
            name='model_file',
            field=models.CharField(max_length=200),
        ),
    ]
