# Generated by Django 2.2.5 on 2022-05-26 20:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0080_auto_20211213_0718'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalchapter',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Chapter', 'verbose_name_plural': 'historical Chapters'},
        ),
        migrations.AlterModelOptions(
            name='historicaldeadline',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Deadline', 'verbose_name_plural': 'historical Deadlines'},
        ),
        migrations.AlterModelOptions(
            name='historicalexerciseset',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Exercise Set', 'verbose_name_plural': 'historical Exercises Sets'},
        ),
        migrations.AlterModelOptions(
            name='historicalonlineclass',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical OnlineClass', 'verbose_name_plural': 'historical OnlineClasses'},
        ),
        migrations.AlterModelOptions(
            name='historicalproblem',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Problem', 'verbose_name_plural': 'historical Problems'},
        ),
        migrations.AlterModelOptions(
            name='historicalprofessor',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical professor', 'verbose_name_plural': 'historical Professors'},
        ),
        migrations.AlterModelOptions(
            name='historicalsolution',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Solution', 'verbose_name_plural': 'historical Solutions'},
        ),
        migrations.AlterModelOptions(
            name='historicaltestcase',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Test Case', 'verbose_name_plural': 'historical Test Cases'},
        ),
        migrations.AlterModelOptions(
            name='historicaluserprofile',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical User profile', 'verbose_name_plural': 'historical User profiles'},
        ),
        migrations.AddField(
            model_name='historicaluserprofile',
            name='registration',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='historicaluserprofile',
            name='university',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='registration',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='university',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='historicalchapter',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicaldeadline',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalexerciseset',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalonlineclass',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalproblem',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalprofessor',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalsolution',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicaltestcase',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicaluserprofile',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='userlogerror',
            name='userlog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='error', to='questions.UserLog'),
        ),
    ]
