# Generated by Django 3.2.15 on 2023-08-24 13:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('questions', '0081_auto_20220526_1755'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaluserprofile',
            name='course',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='professor',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True),
        ),
    ]
