# Generated by Django 3.2.23 on 2024-03-28 14:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('questions', '0082_auto_20230817_1804'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
