# Generated by Django 3.2.20 on 2024-04-08 21:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('questions', '0082_auto_20230817_1804'),
    ]

    operations = [
        migrations.CreateModel(
            name='DropoutRisk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('risk', models.DecimalField(decimal_places=2, max_digits=5)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        # migrations.AlterModelOptions(
        #     name='historicalchapter',
        #     options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Chapter', 'verbose_name_plural': 'historical Chapters'},
        # ),
        # migrations.AlterModelOptions(
        #     name='historicaldeadline',
        #     options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Deadline', 'verbose_name_plural': 'historical Deadlines'},
        # ),
        # migrations.AlterModelOptions(
        #     name='historicalexerciseset',
        #     options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Exercise Set', 'verbose_name_plural': 'historical Exercises Sets'},
        # ),
        # migrations.AlterModelOptions(
        #     name='historicalonlineclass',
        #     options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical OnlineClass', 'verbose_name_plural': 'historical OnlineClasses'},
        # ),
        # migrations.AlterModelOptions(
        #     name='historicalproblem',
        #     options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Problem', 'verbose_name_plural': 'historical Problems'},
        # ),
        # migrations.AlterModelOptions(
        #     name='historicalprofessor',
        #     options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical professor', 'verbose_name_plural': 'historical Professors'},
        # ),
        # migrations.AlterModelOptions(
        #     name='historicalsolution',
        #     options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Solution', 'verbose_name_plural': 'historical Solutions'},
        # ),
        # migrations.AlterModelOptions(
        #     name='historicaltestcase',
        #     options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Test Case', 'verbose_name_plural': 'historical Test Cases'},
        # ),
        # migrations.AlterModelOptions(
        #     name='historicaluserprofile',
        #     options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical User profile', 'verbose_name_plural': 'historical User profiles'},
        # ),
        # migrations.AddField(
        #     model_name='historicaluserprofile',
        #     name='course',
        #     field=models.CharField(max_length=200, null=True),
        # ),
        # migrations.AddField(
        #     model_name='userlog',
        #     name='test_case_hits',
        #     field=models.IntegerField(blank=True, null=True),
        # ),
        # migrations.AddField(
        #     model_name='userprofile',
        #     name='course',
        #     field=models.CharField(max_length=200, null=True),
        # ),
        # migrations.AlterField(
        #     model_name='historicalchapter',
        #     name='history_date',
        #     field=models.DateTimeField(db_index=True),
        # ),
        # migrations.AlterField(
        #     model_name='historicaldeadline',
        #     name='history_date',
        #     field=models.DateTimeField(db_index=True),
        # ),
        # migrations.AlterField(
        #     model_name='historicalexerciseset',
        #     name='history_date',
        #     field=models.DateTimeField(db_index=True),
        # ),
        # migrations.AlterField(
        #     model_name='historicalonlineclass',
        #     name='history_date',
        #     field=models.DateTimeField(db_index=True),
        # ),
        # migrations.AlterField(
        #     model_name='historicalproblem',
        #     name='history_date',
        #     field=models.DateTimeField(db_index=True),
        # ),
        # migrations.AlterField(
        #     model_name='historicalprofessor',
        #     name='history_date',
        #     field=models.DateTimeField(db_index=True),
        # ),
        # migrations.AlterField(
        #     model_name='historicalsolution',
        #     name='history_date',
        #     field=models.DateTimeField(db_index=True),
        # ),
        # migrations.AlterField(
        #     model_name='historicaltestcase',
        #     name='history_date',
        #     field=models.DateTimeField(db_index=True),
        # ),
        # migrations.AlterField(
        #     model_name='historicaluserprofile',
        #     name='history_date',
        #     field=models.DateTimeField(db_index=True),
        # ),
        # migrations.AlterField(
        #     model_name='professor',
        #     name='user',
        #     field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True),
        # ),
        migrations.DeleteModel(
            name='Recommendations',
        ),
    ]
