# Generated by Django 3.2.20 on 2024-04-12 21:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('questions', '0083_auto_20240328_1115'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalchapter',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
