# Generated by Django 3.2.25 on 2024-05-02 14:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('questions', '0085_auto_20240412_2147'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collaborator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=1000)),
                ('active', models.BooleanField(default=True)),
                ('image', models.ImageField(upload_to='static/img/equipe/')),
            ],
            options={
                'verbose_name': 'Collaborator',
                'verbose_name_plural': 'Collaborators',
            },
        ),
        # migrations.AddField(
        #     model_name='historicaluserprofile',
        #     name='course',
        #     field=models.CharField(max_length=200, null=True),
        # ),
        # migrations.AddField(
        #     model_name='userlog',
        #     name='test_case_hits',
        #     field=models.IntegerField(blank=True, null=True),
        # ),
        # migrations.AddField(
        #     model_name='userprofile',
        #     name='course',
        #     field=models.CharField(max_length=200, null=True),
        # ),
        # migrations.AlterField(
        #     model_name='professor',
        #     name='user',
        #     field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True),
        # ),
    ]
