# Generated by Django 3.2.25 on 2024-08-06 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0086_auto_20240502_1116'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chapter',
            name='active',
        ),
        migrations.RemoveField(
            model_name='historicalchapter',
            name='active',
        ),
        migrations.AddField(
            model_name='historicalsolution',
            name='language',
            field=models.CharField(choices=[('Python', 'Python'), ('Julia', 'Julia'), ('C', 'C')], default='Python', max_length=20),
        ),
        migrations.AddField(
            model_name='historicaluserprofile',
            name='course',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='solution',
            name='language',
            field=models.CharField(choices=[('Python', 'Python'), ('Julia', 'Julia'), ('C', 'C')], default='Python', max_length=20),
        ),
        migrations.AddField(
            model_name='userlog',
            name='test_case_hits',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='course',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
