# Generated by Django 3.2.25 on 2024-08-07 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0087_auto_20240806_1941'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsolution',
            name='return_type',
            field=models.CharField(blank=True, choices=[('int', 'int'), ('float', 'float'), ('double', 'double'), ('char', 'char')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='solution',
            name='return_type',
            field=models.CharField(blank=True, choices=[('int', 'int'), ('float', 'float'), ('double', 'double'), ('char', 'char')], max_length=50, null=True),
        ),
    ]
