# Generated by Django 3.2.25 on 2024-09-18 03:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('questions', '0087_auto_20240918_0018'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='link',
            field=models.ManyToManyField(blank=True, to='questions.ChapterLink'),
        ),
        # migrations.AddField(
        #     model_name='historicaluserprofile',
        #     name='course',
        #     field=models.CharField(max_length=200, null=True),
        # ),
        # migrations.AddField(
        #     model_name='userlog',
        #     name='test_case_hits',
        #     field=models.IntegerField(blank=True, null=True),
        # ),
        # migrations.AddField(
        #     model_name='userprofile',
        #     name='course',
        #     field=models.CharField(max_length=200, null=True),
        # ),
        # migrations.AlterField(
        #     model_name='professor',
        #     name='user',
        #     field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True),
        # ),
    ]
