# Generated by Django 3.2.25 on 2024-08-09 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0088_auto_20240807_1915'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlog',
            name='language',
            field=models.CharField(default='Python', max_length=20),
        ),
    ]
