# Generated by Django 3.2.25 on 2024-08-20 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0089_userlog_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalsolution',
            name='return_type',
            field=models.CharField(blank=True, choices=[('int', 'int'), ('float', 'float'), ('double', 'double'), ('char', 'char'), ('long', 'long'), ('long long', 'long long'), ('short', 'short'), ('unsigned int', 'unsigned int'), ('unsigned long', 'unsigned long'), ('const char*', 'const char*')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='solution',
            name='return_type',
            field=models.CharField(blank=True, choices=[('int', 'int'), ('float', 'float'), ('double', 'double'), ('char', 'char'), ('long', 'long'), ('long long', 'long long'), ('short', 'short'), ('unsigned int', 'unsigned int'), ('unsigned long', 'unsigned long'), ('const char*', 'const char*')], max_length=50, null=True),
        ),
    ]
