# Generated by Django 3.2.25 on 2024-09-05 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0091_language'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalsolution',
            name='language',
        ),
        migrations.RemoveField(
            model_name='solution',
            name='language',
        ),
        migrations.RemoveField(
            model_name='userlog',
            name='language',
        ),
    ]
