# Generated by Django 3.2.25 on 2024-09-05 22:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0092_auto_20240905_1906'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsolution',
            name='language',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='questions.language'),
        ),
        migrations.AddField(
            model_name='solution',
            name='language',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='questions.language'),
        ),
        migrations.AddField(
            model_name='userlog',
            name='language',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='questions.language'),
        ),
    ]
