# Generated by Django 3.2.25 on 2024-11-01 21:20

from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0094_auto_20240905_2321'),
    ]

    operations = [
        migrations.RunSQL(  #Populando a tabela de linguagens
            sql="""
            DO $$
            BEGIN
                IF NOT EXISTS (SELECT 1 FROM questions_language) THEN
                    INSERT INTO questions_language (name) VALUES ('Python'), ('Julia'), ('C');
                END IF;
            END $$;
            """,
            reverse_sql=""    #Não vou excluir as linguagens, pois elas podem estar sendo usadas por outras tabelas
        ),
        migrations.RunSQL(  #Populando a tabela de relação entre testcases e linguagens e removendo casos de teste para Julia e C de algumas questões
            sql="""
            DO $$
            BEGIN
                IF NOT EXISTS (SELECT 1 FROM questions_testcase_languages) THEN
                    INSERT INTO questions_testcase_languages (testcase_id, language_id)
                    SELECT a.id, b.id
                    FROM questions_testcase a, questions_language b;
                END IF;
            END $$;
            delete from questions_testcase_languages where (language_id=2 or language_id=3) and testcase_id in (select id from questions_testcase where problem_id = 742 and content like '%\\\%');
            delete from questions_testcase_languages where (language_id=2 or language_id=3) and testcase_id in (select id from questions_testcase where problem_id = 831 and content like '%\\\%');
            delete from questions_testcase_languages where (language_id=2 or language_id=3) and testcase_id in (select id from questions_testcase where problem_id = 820 and content like '%\\\%');
            """,
            reverse_sql="TRUNCATE TABLE questions_testcase_languages RESTART IDENTITY;"    #Removendo os registros da tabela e reiniciando a contagem de IDs
        ),
    ]
