# Generated by Django 3.2.25 on 2024-12-06 21:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0095_auto_20241101_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solution',
            name='language',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='questions.language'),
        ),
    ]
