# Generated by Django 3.2.25 on 2024-12-17 00:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0096_auto_20241206_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlog',
            name='language',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='questions.language'),
        )
    ]
