# Generated by Django 3.2.25 on 2024-12-18 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0097_auto_20241216_2124'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChapterLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('name', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='chapter',
            name='link',
            field=models.ManyToManyField(blank=True, to='questions.ChapterLink'),
        ),
    ]
