# Generated by Django 3.2.25 on 2025-01-30 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0098_auto_20241218_1544'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='historicalchapter',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
