# Generated by Django 3.2.25 on 2026-04-09 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0101_auto_20260326_1050'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='turmas',
            field=models.ManyToManyField(blank=True, related_name='problems', to='questions.OnlineClass'),
        ),
    ]
