# Generated by Django 3.2.25 on 2026-04-09 01:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0102_problem_turmas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='turmas',
        ),
    ]
