# Generated by Django 3.2.25 on 2026-05-14 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0103_remove_problem_turmas'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollaboratorImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base64', models.TextField()),
                ('collaborator', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='questions.collaborator')),
            ],
        ),
        migrations.RemoveField(
            model_name='groupcomment',
            name='author',
        ),
        migrations.RemoveField(
            model_name='groupcomment',
            name='group',
        ),
        migrations.RemoveField(
            model_name='groupcomment',
            name='problem',
        ),
        migrations.RemoveField(
            model_name='groupcomment',
            name='user',
        ),
        migrations.DeleteModel(
            name='IgnoredSolution',
        ),
        migrations.AlterUniqueTogether(
            name='solutiongroup',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='solutiongroup',
            name='problem',
        ),
        migrations.RemoveField(
            model_name='solutiongroup',
            name='turma',
        ),
        migrations.DeleteModel(
            name='GroupComment',
        ),
        migrations.DeleteModel(
            name='SolutionGroup',
        ),
    ]
