# Generated by Django 3.2.25 on 2025-06-06 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0083_auto_20240408_1842'),
        ('questions', '0104_create_view_user_chapter_submissions'),
    ]

    operations = [
    ]
