# Generated by Django 3.2.25 on 2026-05-14 20:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('questions', '0104_auto_20260514_1746'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Group Comment',
                'verbose_name_plural': 'Group Comments',
            },
        ),
        migrations.CreateModel(
            name='IgnoredSolution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solution_id', models.CharField(max_length=20)),
                ('problem_id', models.IntegerField()),
                ('reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Ignored Solution',
                'verbose_name_plural': 'Ignored Solutions',
            },
        ),
        migrations.CreateModel(
            name='SolutionGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_index', models.IntegerField(help_text="ID do grupo conforme o solutions.json (campo 'id')")),
                ('correct', models.BooleanField(help_text='Se o grupo passa todos os testes')),
                ('members', models.JSONField(help_text='Lista de IDs das soluções/alunos pertencentes ao grupo')),
                ('count', models.IntegerField(help_text='Quantidade de soluções no grupo')),
                ('representative_code', models.TextField(help_text='Código representativo do grupo (gerado automaticamente pelo Overcode)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solution_groups', to='questions.problem')),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solution_groups', to='questions.onlineclass')),
            ],
            options={
                'verbose_name': 'Solution Group',
                'verbose_name_plural': 'Solution Groups',
            },
        ),
        migrations.AddIndex(
            model_name='ignoredsolution',
            index=models.Index(fields=['problem_id'], name='overcode_ig_problem_b6e134_idx'),
        ),
        migrations.AddField(
            model_name='groupcomment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='questions.professor'),
        ),
        migrations.AddField(
            model_name='groupcomment',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='overcode.solutiongroup'),
        ),
        migrations.AddField(
            model_name='groupcomment',
            name='problem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='questions.problem'),
        ),
        migrations.AddField(
            model_name='groupcomment',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Aluno que recebe o comentário (individual ou ignorado)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='solutiongroup',
            unique_together={('problem', 'turma', 'group_index')},
        ),
        migrations.AddIndex(
            model_name='groupcomment',
            index=models.Index(fields=['problem'], name='overcode_gr_problem_bbc4a6_idx'),
        ),
        migrations.AddIndex(
            model_name='groupcomment',
            index=models.Index(fields=['group'], name='overcode_gr_group_i_ac078e_idx'),
        ),
        migrations.AddIndex(
            model_name='groupcomment',
            index=models.Index(fields=['user'], name='overcode_gr_user_id_7aa478_idx'),
        ),
    ]
