# Generated by Django 3.2.25 on 2026-06-24 23:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0105_userlogview_new_fields'),
        ('overcode', '0002_groupcomment_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='LLMCommentEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('helpful', models.BooleanField()),
                ('correct', models.BooleanField()),
                ('improve', models.BooleanField()),
                ('understand', models.BooleanField()),
                ('contains_code', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('comment', models.OneToOneField(help_text='Comentário gerado por IA avaliado pelo professor', on_delete=django.db.models.deletion.CASCADE, related_name='llm_evaluation', to='overcode.groupcomment')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='llm_comment_evaluations', to='questions.professor')),
            ],
            options={
                'verbose_name': 'LLM Comment Evaluation',
                'verbose_name_plural': 'LLM Comment Evaluations',
            },
        ),
        migrations.AddIndex(
            model_name='llmcommentevaluation',
            index=models.Index(fields=['professor'], name='overcode_ll_profess_f141fc_idx'),
        ),
        migrations.AddIndex(
            model_name='llmcommentevaluation',
            index=models.Index(fields=['comment'], name='overcode_ll_comment_51eda6_idx'),
        ),
    ]
