# Generated by Django 3.2.25 on 2026-06-25 00:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def backfill_llm_evaluation_context(apps, schema_editor):
    LLMCommentEvaluation = apps.get_model("overcode", "LLMCommentEvaluation")
    UserProfile = apps.get_model("questions", "UserProfile")

    for evaluation in LLMCommentEvaluation.objects.select_related(
        "comment",
        "comment__group",
        "comment__problem",
        "comment__user",
    ):
        comment = evaluation.comment

        evaluation.problem_id = comment.problem_id
        evaluation.group_id = comment.group_id
        evaluation.user_id = comment.user_id

        if comment.group_id:
            evaluation.turma_id = comment.group.turma_id
            if comment.user_id:
                evaluation.target_type = "individual"
            else:
                evaluation.target_type = "representative"
        elif comment.user_id:
            profile = UserProfile.objects.filter(user_id=comment.user_id).first()
            if profile:
                evaluation.turma_id = profile.user_class_id
            evaluation.target_type = "ignored"

        evaluation.save(update_fields=[
            "problem",
            "turma",
            "group",
            "user",
            "target_type",
        ])


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('questions', '0105_userlogview_new_fields'),
        ('overcode', '0003_auto_20260624_2046'),
    ]

    operations = [
        migrations.AddField(
            model_name='llmcommentevaluation',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='llm_comment_evaluations', to='overcode.solutiongroup'),
        ),
        migrations.AddField(
            model_name='llmcommentevaluation',
            name='problem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='llm_comment_evaluations', to='questions.problem'),
        ),
        migrations.AddField(
            model_name='llmcommentevaluation',
            name='target_type',
            field=models.CharField(blank=True, choices=[('representative', 'Código representativo'), ('individual', 'Solução individual'), ('ignored', 'Solução ignorada')], help_text='Tipo de código avaliado pelo comentário IA', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='llmcommentevaluation',
            name='turma',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='llm_comment_evaluations', to='questions.onlineclass'),
        ),
        migrations.AddField(
            model_name='llmcommentevaluation',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Aluno avaliado quando o comentário é individual ou ignorado', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='llm_comment_evaluations_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(
            backfill_llm_evaluation_context,
            migrations.RunPython.noop,
        ),
        migrations.AddIndex(
            model_name='llmcommentevaluation',
            index=models.Index(fields=['problem', 'turma'], name='overcode_ll_problem_a9164a_idx'),
        ),
        migrations.AddIndex(
            model_name='llmcommentevaluation',
            index=models.Index(fields=['group'], name='overcode_ll_group_i_22165d_idx'),
        ),
        migrations.AddIndex(
            model_name='llmcommentevaluation',
            index=models.Index(fields=['user'], name='overcode_ll_user_id_dfdb3a_idx'),
        ),
        migrations.AddIndex(
            model_name='llmcommentevaluation',
            index=models.Index(fields=['target_type'], name='overcode_ll_target__af3a21_idx'),
        ),
    ]
